In [3]:
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
c=a+b
d=a-b
e=a*b
f=np.dot(a,b)
a_transpose=a.T
print("addition:")
print(c)
print("substraction:")
print(d)
print("element wise multiplication:")
print(e)
print("multiplication:")
print(f)
print("transpose:")
print(a_transpose)


addition:
[[ 6  8]
 [10 12]]
substraction:
[[-4 -4]
 [-4 -4]]
element wise multiplication
[[ 5 12]
 [21 32]]
multiplication:
[[19 22]
 [43 50]]
transpose:
[[1 3]
 [2 4]]
